wutsi:
  platform:
    cache:
      type: memcached
      memcached:
        username: ${MEMCACHIER_USERNAME}
        password: ${MEMCACHIER_PASSWORD}
        servers: ${MEMCACHIER_SERVERS}
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}
