server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 512

management:
  endpoint:
    health:
      show-details: always
    info:
      git:
        mode: full
  endpoints:
    web:
      exposure:
        include: "beans,flyway,health,info,scheduledtasks"

spring:
  main:
    lazy-initialization: false

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    default-property-inclusion: non_null

wutsi:
  application:
    name: wutsi-gateway
  bff:
    onboard: https://wutsi-onboard-bff-test.herokuapp.com
    cash: https://wutsi-cash-bff-test.herokuapp.com
    login: https://wutsi-login-bff-test.herokuapp.com
    shell: https://wutsi-shell-bff-test.herokuapp.com

zuul:
  routes:
    onboard:
      path: /onboard/**
      url: ${wutsi.bff.onboard}
      sensitiveHeaders:
    login:
      path: /login/**
      url: ${wutsi.bff.login}
      sensitiveHeaders:
    shell:
      path: /shell/**
      url: ${wutsi.bff.shell}
      sensitiveHeaders:
    cash:
      path: /cash/**
      url: ${wutsi.bff.cash}
      sensitiveHeaders:

logging:
  level:
    root: INFO
    com.netflix.zuul: DEBUG
  pattern:
    console: "%d type=%level logger=%class{20} thread=%thread :%m%n"
    file: "%d type=%level logger=%class{20} thread=%thread :%m%n"

